# Generated by Django 4.2.6 on 2023-10-14 11:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("groundwater", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="GroundWater",
        ),
    ]
